PROGNAME = fairytale
CFLAGS = -std=c++11 -O2 -Wall -s -DBIT32
LFLAGS = -lz
TRANSFORMSCPP = transforms/zlibtransform.cpp
PARSERSCPP = parsers/ddsparser.cpp parsers/modparser.cpp parsers/textparser.cpp parsers/jsonparser.cpp
MAINCPP = analyser.cpp block.cpp deduper.cpp filestream.cpp hybridstream.cpp storagemanager.cpp

.PHONY: all
all: $(PROGNAME)

.PHONY: clean
clean:
	rm -f *.o

$(PROGNAME):
	c++ $(CFLAGS) $(TRANSFORMSCPP) $(PARSERSCPP) $(MAINCPP) $(LFLAGS) fairytale.cpp -ofairytale
